# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: &default
  adapter: postgresql
  database: addressBook_development
  encoding: utf8
  min_messages: warning
  pool: 5
  reaping_frequency: 10
  timeout: 5000

test:
  <<: *default
  database: addressBook_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>