# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ad624d6cabe31680d3a98a650689b750b2106075e72a37ad08450034d079723a182f96fcb8f11442ca25caf7e8f0222d05a841ba55be51741ca37b719498b6

test:
  secret_key_base: 979b427fa99c49e085ebcdd8e86f46ef93b6dc8f0de475d45168f806db256199b0228ac64868c442cdb0e6afcff4d10cb27fa99c49e085e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
